# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.box = "debian/buster64"
  config.ssh.forward_x11 = true
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = 4096
  config.vm.provision "build",
    type: "shell", 
    path: "build_ee_android.sh", 
    run: 'always', 
    privileged: false
   
  end

  config.vm.hostname = "bridgesim-ee"


end
